spring.application.name=demo


spring.datasource.url=jdbc:mysql://db-garagebenz-final-pavel.mysql.database.azure.com:3306/garagebenz?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true&requireSSL=false
spring.datasource.username=adminpaveldb
spring.datasource.password=Admin2104
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true



server.port=3000
server.servlet.context-path=/api


app.jwt.secret=586E62725B75323033353436382F423F4528482B4B6250655368566D59713374
app.jwt.expiration-ms=86400000


server.error.include-message=always
server.error.include-binding-errors=always